# Generated by Django 4.1.5 on 2023-02-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, verbose_name='Номер гаража')),
            ],
            options={
                'verbose_name': 'гараж',
                'verbose_name_plural': 'гаражи',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'парк',
                'verbose_name_plural': 'парки',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, verbose_name='Номер билета')),
            ],
            options={
                'verbose_name': 'билет',
                'verbose_name_plural': 'билеты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата транзакции')),
                ('card_number', models.CharField(max_length=52, verbose_name='номер карты')),
                ('ticket_type', models.CharField(max_length=8, verbose_name='тип билета')),
                ('payment_fact', models.BooleanField(verbose_name='факт оплаты')),
                ('route_code', models.CharField(max_length=8, verbose_name='тип билета')),
                ('garage_number', models.CharField(max_length=8, verbose_name='тип билета')),
                ('flight_number', models.CharField(max_length=8, verbose_name='номер рейса')),
                ('validator_number', models.CharField(max_length=8, verbose_name='номер валидатора')),
                ('validator_type', models.CharField(max_length=8, verbose_name='тип валидатора')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
    ]
