# Generated by Django 4.1.5 on 2023-01-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата транзакции')),
                ('card_number', models.CharField(max_length=52, verbose_name='номер карты')),
                ('payment_fact', models.BooleanField(verbose_name='факт оплаты')),
                ('ticket_type', models.CharField(max_length=8, verbose_name='тип билета')),
                ('route_code', models.CharField(max_length=8, verbose_name='тип билета')),
                ('garage_number', models.CharField(max_length=8, verbose_name='тип билета')),
                ('flight_number', models.CharField(max_length=8, verbose_name='номер рейса')),
                ('validator_number', models.CharField(max_length=8, verbose_name='номер валидатора')),
                ('validator_type', models.CharField(max_length=8, verbose_name='тип валидатора')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
    ]
