version: '3.9'

services:

  # postgresdb:
  #   image: postgres:alpine
  #   restart: always
  #   mem_limit: 256m
  #   environment:
  #     POSTGRES_DB: phytonyms.dev
  #     POSTGRES_USER: phytonyms.dev
  #     POSTGRES_PASSWORD: phytonyms.dev
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: "3"
  #   volumes:
  #     - .data/postgresdb:/var/lib/postgresql/data
  #     - .logs/postgresdb:/var/logs
  #     - .tmp/postgresdb:/tmp
  #     - type: bind
  #       source: .history/postgresdb/.bash_history
  #       target: /root/.ash_history
  #     # copy the sql script to create tables
  #     # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  service:
    image: "usalko/test4:v1${DOCKER_TAG_SUFFIX}"
    restart: always
    mem_limit: 256m
    environment:
      # DJANGO_PRODUCTION: 'True'
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - .logs/test4:/var/log
      - .tmp/test4:/tmp
      - type: bind
        source: .history/test4/.bash_history
        target: /root/.ash_history

  front:
    image: "usalko/test4:front${DOCKER_TAG_SUFFIX}"
    restart: always
    mem_limit: 64m
    volumes:
      - .logs/front:/var/log
      - .tmp/front:/tmp
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - test4
    environment:
      EXPOSE_PORT: ${HTTP_PORT}
    ports:
      - "${HTTP_PORT}:80"

